apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-deployment
  template:
    metadata:
      labels:
        app: busybox-deployment
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - sleep
            - "3600"